name: Luacheck

on: [pull_request, push]

permissions:
  contents: read

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: lunarmodules/luacheck@v1
